[package]
name = "autoparser"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["debug", "from", "try_from", "try_into"] }
macro_rules_attribute = "0.2.2"
