[package]
name = "autoparser"
version = "0.1.0"
edition = "2024"

[dependencies]
annotate-snippets = "0.12.4"
derive_more = { version = "2.0.1", features = ["debug", "from", "try_from", "try_into"] }
itertools = "0.14.0"
macro_rules_attribute = "0.2.2"
